-- sentence_problems 테이블에 추가 데이터 삽입 (중복 데이터 포함)

INSERT INTO sentence_problems (id, korean_sentence, english_sentence, source, target_words, word_count, level) VALUES
(gen_random_uuid(), '그는 사과를 가지고 있어요.', 'He have an apple.', '기적의파닉스1권', '["He", "have", "apple", "an"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그녀는 박쥐를 봐요.', 'She see a bat.', '기적의파닉스1권', '["She", "see", "bat", "a"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 내 가방을 좋아해요.', 'I like my bag.', '기적의파닉스1권', '["I", "like", "bag", "my"]', 4, 'BEGINNER'),
(gen_random_uuid(), '당신은 버스를 원하지 않아요.', 'You don''t want the bus.', '기적의파닉스1권', '["You", "don''t", "want", "bus", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '고양이는 슬퍼요.', 'The cat is sad.', '기적의파닉스1권', '["cat", "sad", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '아빠는 행복해요.', 'Dad is good.', '기적의파닉스1권', '["Dad", "good"]', 3, 'BEGINNER'),
(gen_random_uuid(), '그 개는 뚱뚱해요.', 'The dog is fat.', '기적의파닉스1권', '["dog", "fat", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '우리는 노란색 점을 봐요.', 'We see a yellow dot.', '기적의파닉스1권', '["We", "see", "yellow", "dot", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그 코끼리는 커요.', 'The elephant is big.', '기적의파닉스1권', '["elephant", "big", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 여우를 사랑해요.', 'I love the fox.', '기적의파닉스1권', '["I", "love", "fox", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '팬은 좋은가요?', 'Is the fan good?', '기적의파닉스1권', '["fan", "good", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '당신은 가스를 원하지 않아요.', 'You don''t want gas.', '기적의파닉스1권', '["You", "don''t", "want", "gas"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 좋은 고릴라를 봐요.', 'I see a good gorilla.', '기적의파닉스1권', '["I", "see", "good", "gorilla", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그는 깡총 뛰는 것을 좋아해요.', 'He like to hop.', '기적의파닉스1권', '["He", "like", "hop", "to"]', 4, 'BEGINNER'),
(gen_random_uuid(), '잉크는 빨간색이에요.', 'The ink is red.', '기적의파닉스1권', '["ink", "red", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '이구아나가 왔어요.', 'The iguana come.', '기적의파닉스1권', '["iguana", "come", "the"]', 3, 'BEGINNER'),
(gen_random_uuid(), '제트기가 위에 있어요.', 'The jet is up.', '기적의파닉스1권', '["jet", "up", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '아이가 왔어요.', 'The kid come.', '기적의파닉스1권', '["kid", "come", "the"]', 3, 'BEGINNER'),
(gen_random_uuid(), '왕은 뚱뚱해요.', 'The king is fat.', '기적의파닉스1권', '["king", "fat", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 내 다리를 사랑해요.', 'I love my leg.', '기적의파닉스1권', '["I", "love", "leg", "my"]', 4, 'BEGINNER'),
(gen_random_uuid(), '뚜껑은 노란색이에요.', 'The lid is yellow.', '기적의파닉스1권', '["lid", "yellow", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '당신은 입술을 줘요.', 'You give a lip.', '기적의파닉스1권', '["You", "give", "lip", "a"]', 4, 'BEGINNER'),
(gen_random_uuid(), '지도가 안에 있어요.', 'The map is in.', '기적의파닉스1권', '["map", "in", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '돗자리는 나빠요.', 'The mat is bad.', '기적의파닉스1권', '["mat", "bad", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 좋은 마스크를 원해요.', 'I want a good mask.', '기적의파닉스1권', '["I", "want", "good", "mask", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그물은 커요.', 'The net is big.', '기적의파닉스1권', '["net", "big", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '우리는 견과류를 먹지 않아요.', 'We don''t eat a nut.', '기적의파닉스1권', '["We", "don''t", "eat", "nut", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '문어가 여기에 왔어요.', 'The octopus come here.', '기적의파닉스1권', '["octopus", "come", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '타조가 점프하는 것을 보세요.', 'See an ostrich jump.', '기적의파닉스1권', '["See", "ostrich", "jump", "an", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그녀는 뚱뚱한 돼지를 봐요.', 'She see a fat pig.', '기적의파닉스1권', '["She", "see", "fat", "pig", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 빨간 펜을 원해요.', 'We want a red pen.', '기적의파닉스1권', '["We", "want", "red", "pen", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 퀴즈를 좋아하지 않아요.', 'I don''t like the quiz.', '기적의파닉스1권', '["I", "don''t", "like", "quiz", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '여왕은 나쁜가요?', 'Is the queen bad?', '기적의파닉스1권', '["queen", "bad", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '쥐는 작아요.', 'The rat is small.', '기적의파닉스1권', '["rat", "small", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '숫양이 왔어요.', 'The ram come.', '기적의파닉스1권', '["ram", "come", "the"]', 3, 'BEGINNER'),
(gen_random_uuid(), '해는 빨간색이에요.', 'The sun is red.', '기적의파닉스1권', '["sun", "red", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 슬픈 소년이에요.', 'I am a sad boy.', '기적의파닉스1권', '["I", "sad", "a"]', 4, 'BEGINNER'),
(gen_random_uuid(), '팽이는 노란색이에요.', 'The top is yellow.', '기적의파닉스1권', '["top", "yellow", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '열 명이 왔어요.', 'Ten come.', '기적의파닉스1권', '["ten", "come"]', 2, 'BEGINNER'),
(gen_random_uuid(), '밴은 안에 없어요.', 'The van is not in.', '기적의파닉스1권', '["van", "not", "in", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그는 조끼를 좋아하지 않아요.', 'He no like a vest.', '기적의파닉스1권', '["He", "no", "like", "vest", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 시계를 가지고 싶어요.', 'We want to have a watch.', '기적의파닉스1권', '["We", "want", "have", "watch", "a", "to"]', 6, 'BEGINNER'),
(gen_random_uuid(), '창문은 여기에 없어요.', 'The window is not here.', '기적의파닉스1권', '["window", "not", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '여섯 마리의 쥐가 있어요.', 'Six rat are here.', '기적의파닉스1권', '["six", "rat"]', 4, 'BEGINNER'),
(gen_random_uuid(), '상자는 위에 있어요.', 'The box is up.', '기적의파닉스1권', '["box", "up", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '도끼는 나빠요.', 'The ax is bad.', '기적의파닉스1권', '["ax", "bad", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '동물원에 가고 싶어요.', 'I want to go to the zoo.', '기적의파닉스1권', '["I", "want", "go", "zoo", "to", "the"]', 6, 'BEGINNER'),
(gen_random_uuid(), '나는 노란색을 원해요.', 'I want yellow.', '기적의파닉스1권', '["I", "want", "yellow"]', 3, 'BEGINNER');
