-- sentence_problems 테이블에 데이터 삽입
-- ID는 UUID로 자동 생성, source는 '기적의파닉스1권'으로 설정

INSERT INTO sentence_problems (id, korean_sentence, english_sentence, source, target_words, word_count, level) VALUES
(gen_random_uuid(), '나는 사과를 먹지 않아요.', 'I don''t eat an apple.', '기적의파닉스1권', '["I", "don''t", "eat", "apple", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 악어를 보지 않아요.', 'You don''t see an alligator.', '기적의파닉스1권', '["You", "don''t", "see", "alligator", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 박쥐를 원하지 않아요.', 'We don''t want a bat.', '기적의파닉스1권', '["We", "don''t", "want", "bat", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 가방을 가지고 있지 않아요.', 'I don''t have a bag.', '기적의파닉스1권', '["I", "don''t", "have", "bag", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '당신은 버스를 좋아하지 않아요.', 'You don''t like the bus.', '기적의파닉스1권', '["You", "don''t", "like", "bus", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 고양이를 주지 않아요.', 'We don''t give a cat.', '기적의파닉스1권', '["We", "don''t", "give", "cat", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 모자를 쓰지 않아요.', 'You don''t wear a cap.', '기적의파닉스1권', '["You", "don''t", "wear", "cap", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 멍멍이를 보지 않아요.', 'I don''t see the dog.', '기적의파닉스1권', '["I", "don''t", "see", "dog", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 점을 만들지 않아요.', 'We don''t make a dot.', '기적의파닉스1권', '["We", "don''t", "make", "dot", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 달걀을 원하지 않아요.', 'I don''t want an egg.', '기적의파닉스1권', '["I", "don''t", "want", "egg", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 끝을 원하지 않아요.', 'We don''t want the end.', '기적의파닉스1권', '["We", "don''t", "want", "end", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 코끼리를 보지 않아요.', 'You don''t see an elephant.', '기적의파닉스1권', '["You", "don''t", "see", "elephant", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 여우를 사랑하지 않아요.', 'I don''t love the fox.', '기적의파닉스1권', '["I", "don''t", "love", "fox", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 선풍기를 가지고 있지 않아요.', 'We don''t have a fan.', '기적의파닉스1권', '["We", "don''t", "have", "fan", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 뚱뚱하지 않아요.', 'You don''t are fat.', '기적의파닉스1권', '["You", "don''t", "are", "fat"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 가스를 원하지 않아요.', 'I don''t want gas.', '기적의파닉스1권', '["I", "don''t", "want", "gas"]', 4, 'BEGINNER'),
(gen_random_uuid(), '우리는 고릴라를 좋아하지 않아요.', 'We don''t like a gorilla.', '기적의파닉스1권', '["We", "don''t", "like", "gorilla", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 모자를 쓰지 않아요.', 'You don''t wear a hat.', '기적의파닉스1권', '["You", "don''t", "wear", "hat", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 암탉을 가지고 있지 않아요.', 'I don''t have a hen.', '기적의파닉스1권', '["I", "don''t", "have", "hen", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 깡총 뛰지 않아요.', 'We don''t hop.', '기적의파닉스1권', '["We", "don''t", "hop"]', 3, 'BEGINNER'),
(gen_random_uuid(), '너는 잉크를 주지 않아요.', 'You don''t give ink.', '기적의파닉스1권', '["You", "don''t", "give", "ink"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 이글루를 보지 않아요.', 'I don''t see an igloo.', '기적의파닉스1권', '["I", "don''t", "see", "igloo", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 잼을 만들지 않아요.', 'We don''t make jam.', '기적의파닉스1권', '["We", "don''t", "make", "jam"]', 4, 'BEGINNER'),
(gen_random_uuid(), '너는 제트기를 원하지 않아요.', 'You don''t want a jet.', '기적의파닉스1권', '["You", "don''t", "want", "jet", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 점프하지 않아요.', 'I don''t jump.', '기적의파닉스1권', '["I", "don''t", "jump"]', 3, 'BEGINNER'),
(gen_random_uuid(), '우리는 아이를 원하지 않아요.', 'We don''t want a kid.', '기적의파닉스1권', '["We", "don''t", "want", "kid", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 왕을 보지 않아요.', 'You don''t see the king.', '기적의파닉스1권', '["You", "don''t", "see", "king", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 키위를 좋아하지 않아요.', 'I don''t like kiwi.', '기적의파닉스1권', '["I", "don''t", "like", "kiwi"]', 4, 'BEGINNER'),
(gen_random_uuid(), '우리는 다리를 다치지 않아요.', 'We don''t have bad leg.', '기적의파닉스1권', '["We", "don''t", "have", "bad", "leg"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 뚜껑을 주지 않아요.', 'You don''t give a lid.', '기적의파닉스1권', '["You", "don''t", "give", "lid", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 입술을 가지고 있지 않아요.', 'I don''t have a lip.', '기적의파닉스1권', '["I", "don''t", "have", "lip", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 지도를 만들지 않아요.', 'We don''t make a map.', '기적의파닉스1권', '["We", "don''t", "make", "map", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 돗자리 위에 있지 않아요.', 'You don''t are on the mat.', '기적의파닉스1권', '["You", "don''t", "are", "on", "mat", "the"]', 6, 'BEGINNER'),
(gen_random_uuid(), '나는 마스크를 쓰지 않아요.', 'I don''t wear a mask.', '기적의파닉스1권', '["I", "don''t", "wear", "mask", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 그물을 가지고 있지 않아요.', 'We don''t have a net.', '기적의파닉스1권', '["We", "don''t", "have", "net", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 견과류를 먹지 않아요.', 'You don''t eat a nut.', '기적의파닉스1권', '["You", "don''t", "eat", "nut", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 황소를 보지 않아요.', 'I don''t see an ox.', '기적의파닉스1권', '["I", "don''t", "see", "ox", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 문어를 사랑하지 않아요.', 'We don''t love an octopus.', '기적의파닉스1권', '["We", "don''t", "love", "octopus", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 타조를 보지 않아요.', 'You don''t see an ostrich.', '기적의파닉스1권', '["You", "don''t", "see", "ostrich", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 돼지를 원하지 않아요.', 'I don''t want a pig.', '기적의파닉스1권', '["I", "don''t", "want", "pig", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 펜을 가지고 있지 않아요.', 'We don''t have a pen.', '기적의파닉스1권', '["We", "don''t", "have", "pen", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 퀴즈를 좋아하지 않아요.', 'You don''t like the quiz.', '기적의파닉스1권', '["You", "don''t", "like", "quiz", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 여왕을 보지 않아요.', 'I don''t see the queen.', '기적의파닉스1권', '["I", "don''t", "see", "queen", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 쥐를 주지 않아요.', 'We don''t give a rat.', '기적의파닉스1권', '["We", "don''t", "give", "rat", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 숫양을 사랑하지 않아요.', 'You don''t love the ram.', '기적의파닉스1권', '["You", "don''t", "love", "ram", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 해를 보지 않아요.', 'I don''t see the sun.', '기적의파닉스1권', '["I", "don''t", "see", "sun", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 양말을 가지고 있지 않아요.', 'We don''t have a sock.', '기적의파닉스1권', '["We", "don''t", "have", "sock", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 팽이를 원하지 않아요.', 'You don''t want a top.', '기적의파닉스1권', '["You", "don''t", "want", "top", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 텐트를 가지고 있지 않아요.', 'I don''t have a tent.', '기적의파닉스1권', '["I", "don''t", "have", "tent", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 우산을 원하지 않아요.', 'We don''t want an umbrella.', '기적의파닉스1권', '["We", "don''t", "want", "umbrella", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 수의사를 보지 않아요.', 'You don''t see the vet.', '기적의파닉스1권', '["You", "don''t", "see", "vet", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 밴을 좋아하지 않아요.', 'I don''t like the van.', '기적의파닉스1권', '["I", "don''t", "like", "van", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 조끼를 가지고 있지 않아요.', 'We don''t have a vest.', '기적의파닉스1권', '["We", "don''t", "have", "vest", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 거미줄을 보지 않아요.', 'You don''t see a web.', '기적의파닉스1권', '["You", "don''t", "see", "web", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 시계를 원하지 않아요.', 'I don''t want a watch.', '기적의파닉스1권', '["I", "don''t", "want", "watch", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 창문을 만들지 않아요.', 'We don''t make a window.', '기적의파닉스1권', '["We", "don''t", "make", "window", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '너는 상자를 주지 않아요.', 'You don''t give a box.', '기적의파닉스1권', '["You", "don''t", "give", "box", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 도끼를 가지고 있지 않아요.', 'I don''t have an ax.', '기적의파닉스1권', '["I", "don''t", "have", "ax", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 소리치지 않아요.', 'We don''t yell.', '기적의파닉스1권', '["We", "don''t", "yell"]', 3, 'BEGINNER'),
(gen_random_uuid(), '너는 동물원을 좋아하지 않아요.', 'You don''t like the zoo.', '기적의파닉스1권', '["You", "don''t", "like", "zoo", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 사과를 사랑해요.', 'I love an apple.', '기적의파닉스1권', '["I", "love", "apple", "an"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그는 큰 개를 봐요.', 'He see a big dog.', '기적의파닉스1권', '["He", "see", "dog", "big", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그녀는 빨간 캡을 원해요.', 'She want a red cap.', '기적의파닉스1권', '["She", "want", "red", "cap", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '아빠는 행복해요.', 'Dad is good.', '기적의파닉스1권', '["Dad", "good"]', 3, 'BEGINNER'),
(gen_random_uuid(), '우리는 노란색 점을 봐요.', 'We see yellow dot.', '기적의파닉스1권', '["We", "see", "yellow", "dot"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그는 코끼리를 사랑해요.', 'He love an elephant.', '기적의파닉스1권', '["He", "love", "elephant", "an"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그녀는 뚱뚱한 돼지를 봐요.', 'She see a fat pig.', '기적의파닉스1권', '["She", "see", "fat", "pig", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 빨간 모자를 원해요.', 'I want a red hat.', '기적의파닉스1권', '["I", "want", "red", "hat", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '아이가 왔어요.', 'The kid come.', '기적의파닉스1권', '["kid", "come", "the"]', 3, 'BEGINNER'),
(gen_random_uuid(), '왕이 깡총 뛰는 것을 보세요.', 'See the king hop.', '기적의파닉스1권', '["See", "king", "hop", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그녀는 키위를 먹어요.', 'She eat kiwi.', '기적의파닉스1권', '["She", "eat", "kiwi"]', 3, 'BEGINNER'),
(gen_random_uuid(), '당신은 지도를 사랑해요.', 'You love a map.', '기적의파닉스1권', '["You", "love", "map", "a"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그는 쥐를 주지 않아요.', 'He don''t give a rat.', '기적의파닉스1권', '["He", "don''t", "give", "rat", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '해는 빨간색이에요.', 'The sun is red.', '기적의파닉스1권', '["sun", "red", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '팽이는 노란색이에요.', 'The top is yellow.', '기적의파닉스1권', '["top", "yellow", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '상자는 위에 있어요.', 'The box is up.', '기적의파닉스1권', '["box", "up", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그는 도끼를 가지고 있어요.', 'He have an ax.', '기적의파닉스1권', '["He", "have", "ax", "an"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그것은 나쁜 지그재그예요.', 'It is a bad zigzag.', '기적의파닉스1권', '["It", "bad", "zigzag", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 나쁜 사과를 먹어요.', 'I eat a bad apple.', '기적의파닉스1권', '["I", "eat", "bad", "apple", "an"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그는 큰 밴을 가지고 있어요.', 'He have a big van.', '기적의파닉스1권', '["He", "have", "big", "van", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '당신은 깡총 뛰는 것을 좋아해요.', 'You like hop.', '기적의파닉스1권', '["You", "like", "hop"]', 3, 'BEGINNER'),
(gen_random_uuid(), '그녀는 검은 고양이를 봐요.', 'She see black cat.', '기적의파닉스1권', '["She", "see", "black", "cat"]', 4, 'BEGINNER'),
(gen_random_uuid(), '우리는 버스에 있어요.', 'We are on the bus.', '기적의파닉스1권', '["We", "are", "on", "bus", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '아빠는 모자를 원해요.', 'Dad want a cap.', '기적의파닉스1권', '["Dad", "want", "cap", "a"]', 4, 'BEGINNER'),
(gen_random_uuid(), '개는 깡총 뛸 수 있어요.', 'Dog can hop.', '기적의파닉스1권', '["dog", "can", "hop"]', 3, 'BEGINNER'),
(gen_random_uuid(), '달걀은 돗자리 위에 있어요.', 'The egg is on the mat.', '기적의파닉스1권', '["egg", "on", "mat", "the"]', 6, 'BEGINNER'),
(gen_random_uuid(), '코끼리가 점프하는 것을 보세요.', 'See the elephant jump.', '기적의파닉스1권', '["See", "elephant", "jump", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '팬은 좋은가요?', 'Is the fan good?', '기적의파닉스1권', '["fan", "good", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '고릴라는 슬퍼요.', 'Gorilla is sad.', '기적의파닉스1권', '["gorilla", "sad"]', 3, 'BEGINNER'),
(gen_random_uuid(), '나는 빨간 모자를 가지고 싶어요.', 'I want to have a red hat.', '기적의파닉스1권', '["I", "want", "have", "red", "hat", "a", "to"]', 7, 'BEGINNER'),
(gen_random_uuid(), '암탉이 깡총 뛰는 것을 보세요.', 'See the hen hop.', '기적의파닉스1권', '["See", "hen", "hop", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '아이가 왔어요.', 'The kid come.', '기적의파닉스1권', '["kid", "come", "the"]', 3, 'BEGINNER'),
(gen_random_uuid(), '왕이 깡총 뛰는 것을 보세요.', 'See the king hop.', '기적의파닉스1권', '["See", "king", "hop", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그녀는 키위를 먹어요.', 'She eat kiwi.', '기적의파닉스1권', '["She", "eat", "kiwi"]', 3, 'BEGINNER'),
(gen_random_uuid(), '나는 다리를 봐요.', 'I see my leg.', '기적의파닉스1권', '["I", "see", "leg", "my"]', 4, 'BEGINNER'),
(gen_random_uuid(), '뚜껑은 노란색이에요.', 'The lid is yellow.', '기적의파닉스1권', '["lid", "yellow", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '그는 핑크색 입술을 가지고 있어요.', 'He have pink lip.', '기적의파닉스1권', '["He", "have", "pink", "lip"]', 4, 'BEGINNER'),
(gen_random_uuid(), '당신은 지도를 사랑해요.', 'You love a map.', '기적의파닉스1권', '["You", "love", "map", "a"]', 4, 'BEGINNER'),
(gen_random_uuid(), '돗자리는 나빠요.', 'The mat is bad.', '기적의파닉스1권', '["mat", "bad", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 좋은 마스크를 원해요.', 'I want a good mask.', '기적의파닉스1권', '["I", "want", "good", "mask", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그물은 커요.', 'The net is big.', '기적의파닉스1권', '["net", "big", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '우리는 견과류를 먹지 않아요.', 'We don''t eat a nut.', '기적의파닉스1권', '["We", "don''t", "eat", "nut", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '문어가 여기에 왔어요.', 'The octopus come here.', '기적의파닉스1권', '["octopus", "come", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '타조가 점프하는 것을 보세요.', 'See an ostrich jump.', '기적의파닉스1권', '["See", "ostrich", "jump", "an", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그녀는 뚱뚱한 돼지를 봐요.', 'She see a fat pig.', '기적의파닉스1권', '["She", "see", "fat", "pig", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 빨간 펜을 원해요.', 'We want a red pen.', '기적의파닉스1권', '["We", "want", "red", "pen", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '나는 퀴즈를 좋아하지 않아요.', 'I don''t like the quiz.', '기적의파닉스1권', '["I", "don''t", "like", "quiz", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '여왕은 나쁜가요?', 'Is the queen bad?', '기적의파닉스1권', '["queen", "bad", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '쥐는 작아요.', 'The rat is small.', '기적의파닉스1권', '["rat", "small", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '숫양이 왔어요.', 'The ram come.', '기적의파닉스1권', '["ram", "come", "the"]', 3, 'BEGINNER'),
(gen_random_uuid(), '해는 빨간색이에요.', 'The sun is red.', '기적의파닉스1권', '["sun", "red", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '나는 슬픈 소년이에요.', 'I am a sad boy.', '기적의파닉스1권', '["I", "sad", "a"]', 4, 'BEGINNER'),
(gen_random_uuid(), '팽이는 노란색이에요.', 'The top is yellow.', '기적의파닉스1권', '["top", "yellow", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '열 명이 왔어요.', 'Ten come.', '기적의파닉스1권', '["ten", "come"]', 2, 'BEGINNER'),
(gen_random_uuid(), '밴은 안에 없어요.', 'The van is not in.', '기적의파닉스1권', '["van", "not", "in", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '그는 조끼를 좋아하지 않아요.', 'He no like a vest.', '기적의파닉스1권', '["He", "no", "like", "vest", "a"]', 5, 'BEGINNER'),
(gen_random_uuid(), '우리는 시계를 가지고 싶어요.', 'We want to have a watch.', '기적의파닉스1권', '["We", "want", "have", "watch", "a", "to"]', 6, 'BEGINNER'),
(gen_random_uuid(), '창문은 여기에 없어요.', 'The window is not here.', '기적의파닉스1권', '["window", "not", "the"]', 5, 'BEGINNER'),
(gen_random_uuid(), '여섯 마리의 쥐가 있어요.', 'Six rat are here.', '기적의파닉스1권', '["six", "rat"]', 4, 'BEGINNER'),
(gen_random_uuid(), '상자는 위에 있어요.', 'The box is up.', '기적의파닉스1권', '["box", "up", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '도끼는 나빠요.', 'The ax is bad.', '기적의파닉스1권', '["ax", "bad", "the"]', 4, 'BEGINNER'),
(gen_random_uuid(), '동물원에 가고 싶어요.', 'I want to go to the zoo.', '기적의파닉스1권', '["I", "want", "go", "zoo", "to", "the"]', 6, 'BEGINNER'),
(gen_random_uuid(), '나는 노란색을 원해요.', 'I want yellow.', '기적의파닉스1권', '["I", "want", "yellow"]', 3, 'BEGINNER');
